#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DemoStrideEngineAvatar.Resource", IsApplication=true)]

namespace DemoStrideEngineAvatar
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Stride.Games.Resource.Id.EditTextLayout = global::DemoStrideEngineAvatar.Resource.Id.EditTextLayout;
			global::Stride.Games.Resource.Id.GameMainLayout = global::DemoStrideEngineAvatar.Resource.Id.GameMainLayout;
			global::Stride.Games.Resource.Id.GameViewLayout = global::DemoStrideEngineAvatar.Resource.Id.GameViewLayout;
			global::Stride.Games.Resource.Layout.Game = global::DemoStrideEngineAvatar.Resource.Layout.Game;
			global::Stride.Input.Resource.Id.EditTextLayout = global::DemoStrideEngineAvatar.Resource.Id.EditTextLayout;
			global::Stride.Input.Resource.Id.GameMainLayout = global::DemoStrideEngineAvatar.Resource.Id.GameMainLayout;
			global::Stride.Input.Resource.Id.GameViewLayout = global::DemoStrideEngineAvatar.Resource.Id.GameViewLayout;
			global::Stride.Input.Resource.Layout.Game = global::DemoStrideEngineAvatar.Resource.Layout.Game;
			global::Stride.UI.Resource.Id.EditTextLayout = global::DemoStrideEngineAvatar.Resource.Id.EditTextLayout;
			global::Stride.UI.Resource.Id.GameMainLayout = global::DemoStrideEngineAvatar.Resource.Id.GameMainLayout;
			global::Stride.UI.Resource.Id.GameViewLayout = global::DemoStrideEngineAvatar.Resource.Id.GameViewLayout;
			global::Stride.UI.Resource.Layout.Game = global::DemoStrideEngineAvatar.Resource.Layout.Game;
			global::Stride.VirtualReality.Resource.Color.alignment_marker_color = global::DemoStrideEngineAvatar.Resource.Color.alignment_marker_color;
			global::Stride.VirtualReality.Resource.Color.white_transparent = global::DemoStrideEngineAvatar.Resource.Color.white_transparent;
			global::Stride.VirtualReality.Resource.Dimension.alignment_marker_height = global::DemoStrideEngineAvatar.Resource.Dimension.alignment_marker_height;
			global::Stride.VirtualReality.Resource.Dimension.alignment_marker_thickness = global::DemoStrideEngineAvatar.Resource.Dimension.alignment_marker_thickness;
			global::Stride.VirtualReality.Resource.Dimension.transition_bottom_bar_height = global::DemoStrideEngineAvatar.Resource.Dimension.transition_bottom_bar_height;
			global::Stride.VirtualReality.Resource.Drawable.quantum_ic_close_white_24 = global::DemoStrideEngineAvatar.Resource.Drawable.quantum_ic_close_white_24;
			global::Stride.VirtualReality.Resource.Drawable.quantum_ic_settings_white_24 = global::DemoStrideEngineAvatar.Resource.Drawable.quantum_ic_settings_white_24;
			global::Stride.VirtualReality.Resource.Drawable.rippleable = global::DemoStrideEngineAvatar.Resource.Drawable.rippleable;
			global::Stride.VirtualReality.Resource.Drawable.transition = global::DemoStrideEngineAvatar.Resource.Drawable.transition;
			global::Stride.VirtualReality.Resource.Id.back_button = global::DemoStrideEngineAvatar.Resource.Id.back_button;
			global::Stride.VirtualReality.Resource.Id.divider = global::DemoStrideEngineAvatar.Resource.Id.divider;
			global::Stride.VirtualReality.Resource.Id.EditTextLayout = global::DemoStrideEngineAvatar.Resource.Id.EditTextLayout;
			global::Stride.VirtualReality.Resource.Id.GameMainLayout = global::DemoStrideEngineAvatar.Resource.Id.GameMainLayout;
			global::Stride.VirtualReality.Resource.Id.GameViewLayout = global::DemoStrideEngineAvatar.Resource.Id.GameViewLayout;
			global::Stride.VirtualReality.Resource.Id.transition_bottom_frame = global::DemoStrideEngineAvatar.Resource.Id.transition_bottom_frame;
			global::Stride.VirtualReality.Resource.Id.transition_frame = global::DemoStrideEngineAvatar.Resource.Id.transition_frame;
			global::Stride.VirtualReality.Resource.Id.transition_icon = global::DemoStrideEngineAvatar.Resource.Id.transition_icon;
			global::Stride.VirtualReality.Resource.Id.transition_question_text = global::DemoStrideEngineAvatar.Resource.Id.transition_question_text;
			global::Stride.VirtualReality.Resource.Id.transition_switch_action = global::DemoStrideEngineAvatar.Resource.Id.transition_switch_action;
			global::Stride.VirtualReality.Resource.Id.transition_text = global::DemoStrideEngineAvatar.Resource.Id.transition_text;
			global::Stride.VirtualReality.Resource.Id.transition_top_frame = global::DemoStrideEngineAvatar.Resource.Id.transition_top_frame;
			global::Stride.VirtualReality.Resource.Id.ui_alignment_marker = global::DemoStrideEngineAvatar.Resource.Id.ui_alignment_marker;
			global::Stride.VirtualReality.Resource.Id.ui_back_button = global::DemoStrideEngineAvatar.Resource.Id.ui_back_button;
			global::Stride.VirtualReality.Resource.Id.ui_settings_button = global::DemoStrideEngineAvatar.Resource.Id.ui_settings_button;
			global::Stride.VirtualReality.Resource.Layout.back_button = global::DemoStrideEngineAvatar.Resource.Layout.back_button;
			global::Stride.VirtualReality.Resource.Layout.Game = global::DemoStrideEngineAvatar.Resource.Layout.Game;
			global::Stride.VirtualReality.Resource.Layout.settings_button = global::DemoStrideEngineAvatar.Resource.Layout.settings_button;
			global::Stride.VirtualReality.Resource.Layout.transition_view = global::DemoStrideEngineAvatar.Resource.Layout.transition_view;
			global::Stride.VirtualReality.Resource.Layout.ui_layer = global::DemoStrideEngineAvatar.Resource.Layout.ui_layer;
			global::Stride.VirtualReality.Resource.Layout.ui_layer_with_portrait_support = global::DemoStrideEngineAvatar.Resource.Layout.ui_layer_with_portrait_support;
			global::Stride.VirtualReality.Resource.String.back_button_content_description = global::DemoStrideEngineAvatar.Resource.String.back_button_content_description;
			global::Stride.VirtualReality.Resource.String.cancel_button = global::DemoStrideEngineAvatar.Resource.String.cancel_button;
			global::Stride.VirtualReality.Resource.String.dialog_button_got_it = global::DemoStrideEngineAvatar.Resource.String.dialog_button_got_it;
			global::Stride.VirtualReality.Resource.String.dialog_button_open_help_center = global::DemoStrideEngineAvatar.Resource.String.dialog_button_open_help_center;
			global::Stride.VirtualReality.Resource.String.dialog_message_incompatible_phone = global::DemoStrideEngineAvatar.Resource.String.dialog_message_incompatible_phone;
			global::Stride.VirtualReality.Resource.String.dialog_message_no_cardboard = global::DemoStrideEngineAvatar.Resource.String.dialog_message_no_cardboard;
			global::Stride.VirtualReality.Resource.String.dialog_message_setup = global::DemoStrideEngineAvatar.Resource.String.dialog_message_setup;
			global::Stride.VirtualReality.Resource.String.dialog_title = global::DemoStrideEngineAvatar.Resource.String.dialog_title;
			global::Stride.VirtualReality.Resource.String.dialog_title_incompatible_phone = global::DemoStrideEngineAvatar.Resource.String.dialog_title_incompatible_phone;
			global::Stride.VirtualReality.Resource.String.dialog_title_vr_core_not_enabled = global::DemoStrideEngineAvatar.Resource.String.dialog_title_vr_core_not_enabled;
			global::Stride.VirtualReality.Resource.String.dialog_title_vr_core_not_installed = global::DemoStrideEngineAvatar.Resource.String.dialog_title_vr_core_not_installed;
			global::Stride.VirtualReality.Resource.String.dialog_title_warning = global::DemoStrideEngineAvatar.Resource.String.dialog_title_warning;
			global::Stride.VirtualReality.Resource.String.dialog_vr_core_not_enabled = global::DemoStrideEngineAvatar.Resource.String.dialog_vr_core_not_enabled;
			global::Stride.VirtualReality.Resource.String.dialog_vr_core_not_installed = global::DemoStrideEngineAvatar.Resource.String.dialog_vr_core_not_installed;
			global::Stride.VirtualReality.Resource.String.go_to_playstore_button = global::DemoStrideEngineAvatar.Resource.String.go_to_playstore_button;
			global::Stride.VirtualReality.Resource.String.go_to_vr_listeners_settings_button = global::DemoStrideEngineAvatar.Resource.String.go_to_vr_listeners_settings_button;
			global::Stride.VirtualReality.Resource.String.gvr_vr_mode_component = global::DemoStrideEngineAvatar.Resource.String.gvr_vr_mode_component;
			global::Stride.VirtualReality.Resource.String.no_browser_text = global::DemoStrideEngineAvatar.Resource.String.no_browser_text;
			global::Stride.VirtualReality.Resource.String.place_your_phone_into_cardboard = global::DemoStrideEngineAvatar.Resource.String.place_your_phone_into_cardboard;
			global::Stride.VirtualReality.Resource.String.place_your_viewer_into_viewer_format = global::DemoStrideEngineAvatar.Resource.String.place_your_viewer_into_viewer_format;
			global::Stride.VirtualReality.Resource.String.settings_button_content_description = global::DemoStrideEngineAvatar.Resource.String.settings_button_content_description;
			global::Stride.VirtualReality.Resource.String.setup_button = global::DemoStrideEngineAvatar.Resource.String.setup_button;
			global::Stride.VirtualReality.Resource.String.switch_viewer_action = global::DemoStrideEngineAvatar.Resource.String.switch_viewer_action;
			global::Stride.VirtualReality.Resource.String.switch_viewer_prompt = global::DemoStrideEngineAvatar.Resource.String.switch_viewer_prompt;
			global::Stride.VirtualReality.Resource.Style.GvrDialogTheme = global::DemoStrideEngineAvatar.Resource.Style.GvrDialogTheme;
			global::Stride.VirtualReality.Resource.Style.NoSystemUI = global::DemoStrideEngineAvatar.Resource.Style.NoSystemUI;
			global::Stride.VirtualReality.Resource.Style.UiButton = global::DemoStrideEngineAvatar.Resource.Style.UiButton;
			global::Stride.VirtualReality.Resource.Style.VrActivityTheme = global::DemoStrideEngineAvatar.Resource.Style.VrActivityTheme;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int alignment_marker_color = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int white_transparent = 2130771969;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int alignment_marker_height = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int alignment_marker_thickness = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int transition_bottom_bar_height = 2130837506;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int Icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int quantum_ic_close_white_24 = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int quantum_ic_settings_white_24 = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int rippleable = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int transition = 2130903044;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040003
			public const int back_button = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int divider = 2130968580;
			
			// aapt resource value: 0x7F040000
			public const int EditTextLayout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int GameMainLayout = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int GameViewLayout = 2130968578;
			
			// aapt resource value: 0x7F040005
			public const int transition_bottom_frame = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int transition_frame = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int transition_icon = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int transition_question_text = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int transition_switch_action = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int transition_text = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int transition_top_frame = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int ui_alignment_marker = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int ui_back_button = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int ui_settings_button = 2130968590;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int back_button = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int Game = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int settings_button = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int transition_view = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int ui_layer = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int ui_layer_with_portrait_support = 2131034117;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060000
			public const int back_button_content_description = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int cancel_button = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int dialog_button_got_it = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int dialog_button_open_help_center = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int dialog_message_incompatible_phone = 2131099652;
			
			// aapt resource value: 0x7F060005
			public const int dialog_message_no_cardboard = 2131099653;
			
			// aapt resource value: 0x7F060006
			public const int dialog_message_setup = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int dialog_title = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int dialog_title_incompatible_phone = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int dialog_title_vr_core_not_enabled = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int dialog_title_vr_core_not_installed = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int dialog_title_warning = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int dialog_vr_core_not_enabled = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int dialog_vr_core_not_installed = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int go_to_playstore_button = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int go_to_vr_listeners_settings_button = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int gvr_vr_mode_component = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int no_browser_text = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int place_your_phone_into_cardboard = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int place_your_viewer_into_viewer_format = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int settings_button_content_description = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int setup_button = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int switch_viewer_action = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int switch_viewer_prompt = 2131099671;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int GvrDialogTheme = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int NoSystemUI = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int UiButton = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int VrActivityTheme = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
